name: "\U0001F41E Bug Report"
description: Report a bug to help improve ScribeNEO.
title: "[BUG] <title>"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: textarea
    id: description
    attributes:
      label: "📝 Bug Description"
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "💻 Console Logs"
      description: Copy/paste any error logs from your console here.
      render: bash
    validations:
      required: false      
  - type: input
    id: version
    attributes:
      label: "🛠️ Forge Neo Version"
      description: Which version of Forge Neo are you using?
    validations:
      required: false